version: '3'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
    volumes:
      - ./monitoring/tempo/tempo.yaml:/etc/tempo.yaml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki.yaml:/etc/loki.yaml

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./monitoring/mimir/mimir.yaml:/etc/mimir.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3300:3000"
    volumes:
      - "./monitoring/grafana/definitions:/var/lib/grafana/dashboards"
      - "./monitoring/grafana/provisioning:/etc/grafana/provisioning"
    depends_on:
      - tempo
      - loki
      - mimir